services:
  socketkill:
    build: .
    container_name: site
    restart: always
    env_file:
      - .env
    ports:
      - "8099:8099"
      - "443:443"
    volumes:
      - "./data:/usr/src/app/data"
      - "./ssl:/usr/src/app/ssl"
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"