services:
  killstream-bot:
    build: .
    container_name: kill-stream-bot
    restart: always
    env_file:
      - .env
    ports:
      - "8099:8099"
      - "1098:1098"
    volumes:
      - "./data:/usr/src/app/data"
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"